"use strict";(()=>{var e={};e.id=6322,e.ids=[6322],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},21764:e=>{e.exports=require("util")},8678:e=>{e.exports=import("pg")},18536:(e,t,r)=>{r.a(e,async(e,n)=>{try{r.r(t),r.d(t,{originalPathname:()=>m,patchFetch:()=>u,requestAsyncStorage:()=>c,routeModule:()=>f,serverHooks:()=>p,staticGenerationAsyncStorage:()=>d});var a=r(49303),i=r(88716),l=r(60670),o=r(8142),s=e([o]);o=(s.then?(await s)():s)[0];let f=new a.AppRouteRouteModule({definition:{kind:i.x.APP_ROUTE,page:"/api/offers/route",pathname:"/api/offers",filename:"route",bundlePath:"app/api/offers/route"},resolvedPagePath:"C:\\Users\\mmazur\\source\\repos\\AMSteel_Quote\\finance_calculator_deployed\\nextjs_space\\app\\api\\offers\\route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:c,staticGenerationAsyncStorage:d,serverHooks:p}=f,m="/api/offers/route";function u(){return(0,l.patchFetch)({serverHooks:p,staticGenerationAsyncStorage:d})}n()}catch(e){n(e)}})},8142:(e,t,r)=>{r.a(e,async(e,n)=>{try{r.r(t),r.d(t,{GET:()=>R,POST:()=>I});var a=r(87070),i=r(9487),l=r(67785),o=r(69319),s=r(26409),u=r(60727),f=r(36732),c=r(83173),d=r(31114),p=r(98562),m=r(33359),E=r(49947),_=e([i,u,c,p,E]);[i,u,c,p,E]=_.then?(await _)():_;let L=`o.id, o.offer_name, o.display_name, o.offer_data, o.status, o.user_id,
  o.created_at, o.updated_at, o.reviewed_by, o.reviewed_at, o.rejection_reason, o.sent_at,
  o.root_offer_id, o.version_number, o.flow_id, f.name AS flow_name,
  NOT EXISTS (SELECT 1 FROM offers n
              WHERE COALESCE(n.root_offer_id, n.id) = COALESCE(o.root_offer_id, o.id)
                AND n.version_number > o.version_number) AS is_latest,
  o.client_decision, o.client_decision_at, o.client_decision_note, o.client_decision_reason,
  u.full_name AS owner_name, u.email AS owner_email`;async function R(e){try{let r=await (0,u.nc)();if("error"in r)return r.error;let{ctx:n}=r,o=[],s=(0,f.ar)(n,o,"o"),d=(e.nextUrl.searchParams.get("q")||"").trim();if(d){var t;o.push((0,l.p)(d)),s=`${s} AND ${t=`$${o.length}`,`(
    o.display_name ILIKE '%' || ${t} || '%'
    OR o.id::text = ${t}
    OR o.offer_data->'clientInfo'->>'company' ILIKE '%' || ${t} || '%'
    OR o.offer_data->'clientInfo'->>'sapId' ILIKE '%' || ${t} || '%'
  )`}`}let p=await i.Z.query(`SELECT ${L}
       FROM offers o
       LEFT JOIN users u ON u.id = o.user_id
       LEFT JOIN flows f ON f.id = o.flow_id
       WHERE ${s}
       ORDER BY o.created_at DESC`,o),m=await (0,c.pp)(p.rows.map(e=>Number(e.id))),E=(0,c.DZ)(),_=await Promise.all(p.rows.map(async e=>{let t=e.status,r=m.get(Number(e.id))??[],a="sent"===t?null:(await E({flowId:e.flow_id,ownerId:e.user_id,offerData:e.offer_data})).plan,i=(0,c.un)(n,{userId:e.user_id,flowId:e.flow_id,status:t,isLatest:!0===e.is_latest,clientDecision:e.client_decision},r,a);return{...e,actions:i,pending_levels:r.filter(e=>"pending"===e.status).map(e=>e.levelCode)}}));return a.NextResponse.json({offers:_,userId:n.userId})}catch(e){return console.error("Error fetching offers:",e),a.NextResponse.json({error:"Failed to fetch offers"},{status:500})}}async function I(e){try{let t=await (0,u.nc)();if("error"in t)return t.error;let{ctx:r}=t,n=r.activeFlowId;if(null===n)return(0,m.a)("no_flow");if(!(0,u.BT)(r,n,"canCreateOffer"))return(0,m.a)("cannot_create");let{offer_name:l,offer_data:f}=await e.json().catch(()=>null)??{};if(!f||"object"!=typeof f)return a.NextResponse.json({error:"Missing required fields"},{status:400});let c=(0,E.n)(f);if(c)return a.NextResponse.json({error:c},{status:400});let _=r.memberships.find(e=>e.flowId===n),R=(0,d.G)(r.isSuperuser||!_?"all":_.permissions,f,null,await (0,p.bC)(f.validFrom),await (0,p.xE)());if(R)return(0,m.a)(R);let I="string"==typeof l&&l.trim()?l.trim():null,L=(0,s.MM)(f.clientInfo),y=await i.Z.connect();try{await y.query("BEGIN");let e=await (0,o.LM)(y,L,r.userId),t=await y.query(`INSERT INTO offers (user_id, offer_name, offer_data, client_id, flow_id)
         VALUES ($1, $2, $3, $4, $5)
         RETURNING id, offer_name, display_name, offer_data, status, flow_id, created_at, updated_at`,[r.userId,I,JSON.stringify(f),e,n]);return await y.query("COMMIT"),a.NextResponse.json({offer:t.rows[0]},{status:201})}catch(e){throw await y.query("ROLLBACK").catch(()=>void 0),e}finally{y.release()}}catch(e){return console.error("Error creating offer:",e),a.NextResponse.json({error:"Failed to create offer"},{status:500})}}n()}catch(e){n(e)}})},31114:(e,t,r)=>{function n(e){let t=e?.zestawienie;return Array.isArray(t)?t:[]}r.d(t,{G:()=>l});let a=(e,t)=>1e-6>=Math.abs(e-t);function i(e){if("number"==typeof e)return Number.isFinite(e)?e:null;if("string"==typeof e&&""!==e.trim()){let t=Number(e);return Number.isFinite(t)?t:null}return null}function l(e,t,r,l,o){if("all"===e)return null;let s=n(r);for(let[r,u]of n(t).entries()){let t=function(e,t,r){if(void 0!==t.id&&null!==t.id){let r=e.find(e=>e.id===t.id);if(r)return r}return e[r]}(s,u,r);if(!e.canChangePglBase){let e=i(u.pgl);if(null===e)return"pgl_locked";let r="string"==typeof u.type?l(u.type):Number.NaN,n=i(t?.pgl);if(!a(e,r)&&!(null!==n&&a(n,e)))return"pgl_locked"}let n=u.inputs?.marginPct;if(!e.canChangePriceMargin&&void 0!==n){let e=i(n),r=i(t?.inputs?.marginPct);if(!(null!==e&&(a(e,o)||null!==r&&a(r,e))))return"margin_locked"}}return null}},69319:(e,t,r)=>{async function n(e,t,r){if(""!==r){let t=await e.query("SELECT id FROM clients WHERE LOWER(TRIM(nip)) = LOWER($1) ORDER BY id ASC LIMIT 1",[r]);if(t.rows.length>0)return t.rows[0].id}let n=await e.query("SELECT id FROM clients WHERE LOWER(TRIM(company)) = LOWER($1) ORDER BY id ASC LIMIT 1",[t]);return n.rows.length>0?n.rows[0].id:null}async function a(e,t,r,n){let a=r.firstName.trim(),i=r.lastName.trim();if(""===a&&""===i)return;let l=r.phone.trim(),o=r.email.trim(),s=await e.query(`SELECT id FROM client_contacts
     WHERE client_id = $1
       AND LOWER(TRIM(COALESCE(first_name, ''))) = LOWER($2)
       AND LOWER(TRIM(COALESCE(last_name,  ''))) = LOWER($3)
     ORDER BY id ASC
     LIMIT 1`,[t,a,i]);if(0===s.rows.length){await e.query(`INSERT INTO client_contacts (client_id, first_name, last_name, phone, email, created_by)
       VALUES ($1, $2, $3, $4, $5, $6)`,[t,a||null,i||null,l||null,o||null,n]);return}await e.query(`UPDATE client_contacts
     SET phone      = COALESCE(NULLIF(TRIM(phone), ''), $1),
         email      = COALESCE(NULLIF(TRIM(email), ''), $2),
         updated_at = CURRENT_TIMESTAMP
     WHERE id = $3`,[l||null,o||null,s.rows[0].id])}async function i(e,t,r,n){let a=r.firstName.trim(),i=r.lastName.trim();if(""===a&&""===i)return;let l=r.phone.trim(),o=r.email.trim(),s=await e.query(`SELECT id FROM client_contacts
     WHERE client_id = $1
       AND LOWER(TRIM(COALESCE(first_name, ''))) = LOWER($2)
       AND LOWER(TRIM(COALESCE(last_name,  ''))) = LOWER($3)
     ORDER BY id ASC
     LIMIT 1`,[t,a,i]);if(0===s.rows.length){await e.query(`INSERT INTO client_contacts (client_id, first_name, last_name, phone, email, created_by)
       VALUES ($1, $2, $3, $4, $5, $6)`,[t,a||null,i||null,l||null,o||null,n]);return}await e.query(`UPDATE client_contacts
     SET phone      = $1,
         email      = $2,
         updated_at = CURRENT_TIMESTAMP
     WHERE id = $3`,[l||null,o||null,s.rows[0].id])}async function l(e,t,r){let i=t.company.trim(),l=t.nip.trim();if(""===i)return null;let o=t.address.trim(),s=t.sapId.trim(),u=t.firstName.trim(),f=t.lastName.trim(),c=t.phone.trim(),d=t.email.trim(),p=await n(e,i,l);if(null===p){let n=(await e.query(`INSERT INTO clients (company, nip, address, sap_id, first_name, last_name, phone, email, created_by)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       RETURNING id`,[i,l||null,o||null,s||null,u||null,f||null,c||null,d||null,r])).rows[0].id;return await a(e,n,t,r),n}return await e.query(`UPDATE clients
     SET company    = COALESCE(NULLIF(TRIM(company),    ''), $1),
         nip        = COALESCE(NULLIF(TRIM(nip),        ''), $2),
         address    = COALESCE(NULLIF(TRIM(address),    ''), $3),
         sap_id     = COALESCE(NULLIF(TRIM(sap_id),     ''), $4),
         first_name = COALESCE(NULLIF(TRIM(first_name), ''), $5),
         last_name  = COALESCE(NULLIF(TRIM(last_name),  ''), $6),
         phone      = COALESCE(NULLIF(TRIM(phone),      ''), $7),
         email      = COALESCE(NULLIF(TRIM(email),      ''), $8),
         updated_at = CURRENT_TIMESTAMP
     WHERE id = $9`,[i,l||null,o||null,s||null,u||null,f||null,c||null,d||null,p]),await a(e,p,t,r),p}r.d(t,{LM:()=>l,r8:()=>n,tS:()=>i})},49947:(e,t,r)=>{r.a(e,async(e,n)=>{try{r.d(t,{n:()=>o});var a=r(7410),i=r(54755),l=e([i]);i=(l.then?(await l)():l)[0];let s=a.z.number().finite(),u=s.positive(),f=a.z.object({type:a.z.enum(i.My),grade:a.z.string().trim().min(1),thickness:u,width:u,length:s.nonnegative(),isCoil:a.z.boolean().optional(),tons:u,pgl:u,sumaHuta:s,sumaSSC:s,marza:s,finalPrice:u,totalValue:u,inputs:a.z.object({marginPct:s,extra:s,transport:s}).passthrough().optional()}).passthrough(),c=(e,t)=>.01>=Math.abs(e-t);function o(e){let t=e.zestawienie;if(void 0===t)return null;if(!Array.isArray(t))return"zestawienie must be an array";for(let e=0;e<t.length;e++){let r=f.safeParse(t[e]);if(!r.success){let t=r.error.issues[0];return`Item ${e+1}: invalid ${t.path.join(".")||"item"} (${t.message})`}let n=function(e){if(!e.isCoil&&e.length<=0)return"length must be > 0 for sheets";if(!c(e.totalValue,Math.round(e.finalPrice*e.tons*100)/100))return"totalValue does not equal finalPrice \xd7 tons";if(!e.inputs)return null;let t=e.pgl+e.sumaHuta;if(!c(e.marza,e.inputs.marginPct/100*t))return"marza does not match (PGL + Σ Mill) \xd7 margin %";let r=t+e.marza+e.inputs.extra+e.inputs.transport+e.sumaSSC;return c(e.finalPrice,r)?null:"finalPrice does not equal PGL + Σ Mill + margin + extra + transport + Σ SSC"}(r.data);if(n)return`Item ${e+1}: ${n}`}return null}n()}catch(e){n(e)}})},26409:(e,t,r)=>{r.d(t,{MM:()=>a,uV:()=>i});let n={company:"",nip:"",address:"",sapId:"",firstName:"",lastName:"",phone:"",email:""};function a(e){if(!e||"object"!=typeof e)return{...n};let t=e=>"string"==typeof e?e:"";return{company:t(e.company),nip:t(e.nip),address:t(e.address),sapId:t(e.sapId),firstName:t(e.firstName),lastName:t(e.lastName),phone:t(e.phone),email:t(e.email)}}function i(e){return""!==e.company.trim()&&""!==e.nip.trim()}},67785:(e,t,r)=>{r.d(t,{p:()=>n});function n(e){return e.replace(/[\\%_]/g,e=>`\\${e}`)}}};var t=require("../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),n=t.X(0,[9276,5972,2015,7410,727,5679],()=>r(18536));module.exports=n})();