"use strict";(()=>{var e={};e.id=8192,e.ids=[8192],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},21764:e=>{e.exports=require("util")},8678:e=>{e.exports=import("pg")},59407:(e,r,t)=>{t.a(e,async(e,o)=>{try{t.r(r),t.d(r,{originalPathname:()=>_,patchFetch:()=>p,requestAsyncStorage:()=>c,routeModule:()=>d,serverHooks:()=>f,staticGenerationAsyncStorage:()=>l});var a=t(49303),s=t(88716),n=t(60670),i=t(88558),u=e([i]);i=(u.then?(await u)():u)[0];let d=new a.AppRouteRouteModule({definition:{kind:s.x.APP_ROUTE,page:"/api/admin/offers/route",pathname:"/api/admin/offers",filename:"route",bundlePath:"app/api/admin/offers/route"},resolvedPagePath:"C:\\Users\\mmazur\\source\\repos\\AMSteel_Quote\\finance_calculator_deployed\\nextjs_space\\app\\api\\admin\\offers\\route.ts",nextConfigOutput:"",userland:i}),{requestAsyncStorage:c,staticGenerationAsyncStorage:l,serverHooks:f}=d,_="/api/admin/offers/route";function p(){return(0,n.patchFetch)({serverHooks:f,staticGenerationAsyncStorage:l})}o()}catch(e){o(e)}})},88558:(e,r,t)=>{t.a(e,async(e,o)=>{try{t.r(r),t.d(r,{GET:()=>p});var a=t(87070),s=t(9487),n=t(60727),i=t(67785),u=e([s,n]);[s,n]=u.then?(await u)():u;let d=["draft","pending_review","approved","rejected","sent"];async function p(e){let r=await (0,n.kp)();if("error"in r)return r.error;let t=r.ctx;try{let r=e.nextUrl.searchParams,o=r.get("status"),n=r.get("user_id"),u=r.get("date_from"),p=r.get("date_to"),c="1"===r.get("reviewed_by_me"),l=[],f=[],_=1;o&&d.includes(o)&&(l.push(`o.status = $${_++}`),f.push(o)),n&&(l.push(`o.user_id = $${_++}`),f.push(parseInt(n))),c&&(l.push(`o.reviewed_by = $${_++}`),f.push(t.userId)),u&&(l.push(`o.created_at >= $${_++}`),f.push(u)),p&&(l.push(`o.created_at < ($${_++}::date + interval '1 day')`),f.push(p));let m=(r.get("q")||"").trim();m&&(l.push(`(
        o.display_name ILIKE '%' || $${_} || '%'
        OR o.id::text = $${_}
        OR o.offer_data->'clientInfo'->>'company' ILIKE '%' || $${_} || '%'
        OR o.offer_data->'clientInfo'->>'sapId' ILIKE '%' || $${_} || '%'
      )`),f.push((0,i.p)(m)),_++);let h=l.length>0?`WHERE ${l.join(" AND ")}`:"",x=await s.Z.query(`SELECT o.id, o.offer_name, o.display_name, o.offer_data, o.status, o.user_id,
              o.created_at, o.updated_at, o.reviewed_by, o.reviewed_at,
              o.rejection_reason, o.sent_at, o.root_offer_id, o.version_number, o.client_decision,
              u.full_name AS owner_name, u.email AS owner_email,
              r.full_name AS reviewer_name, r.email AS reviewer_email
       FROM offers o
       LEFT JOIN users u ON u.id = o.user_id
       LEFT JOIN users r ON r.id = o.reviewed_by
       ${h}
       ORDER BY o.created_at DESC`,f);return a.NextResponse.json({offers:x.rows})}catch(e){return console.error("Error fetching admin offers:",e),a.NextResponse.json({error:"Failed to fetch offers"},{status:500})}}o()}catch(e){o(e)}})},67785:(e,r,t)=>{t.d(r,{p:()=>o});function o(e){return e.replace(/[\\%_]/g,e=>`\\${e}`)}}};var r=require("../../../../webpack-runtime.js");r.C(e);var t=e=>r(r.s=e),o=r.X(0,[9276,5972,2015,727],()=>t(59407));module.exports=o})();