"use strict";(()=>{var e={};e.id=7102,e.ids=[7102],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},21764:e=>{e.exports=require("util")},8678:e=>{e.exports=import("pg")},4335:(e,t,r)=>{r.a(e,async(e,n)=>{try{r.r(t),r.d(t,{originalPathname:()=>E,patchFetch:()=>u,requestAsyncStorage:()=>l,routeModule:()=>d,serverHooks:()=>f,staticGenerationAsyncStorage:()=>p});var o=r(49303),i=r(88716),s=r(60670),a=r(63892),c=e([a]);a=(c.then?(await c)():c)[0];let d=new o.AppRouteRouteModule({definition:{kind:i.x.APP_ROUTE,page:"/api/offers/[id]/decision/route",pathname:"/api/offers/[id]/decision",filename:"route",bundlePath:"app/api/offers/[id]/decision/route"},resolvedPagePath:"C:\\Users\\mmazur\\source\\repos\\AMSteel_Quote\\finance_calculator_deployed\\nextjs_space\\app\\api\\offers\\[id]\\decision\\route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:l,staticGenerationAsyncStorage:p,serverHooks:f}=d,E="/api/offers/[id]/decision/route";function u(){return(0,s.patchFetch)({serverHooks:f,staticGenerationAsyncStorage:p})}n()}catch(e){n(e)}})},63892:(e,t,r)=>{r.a(e,async(e,n)=>{try{r.r(t),r.d(t,{POST:()=>p});var o=r(87070),i=r(9487),s=r(60727),a=r(84385),c=r(33359),u=r(76705),d=r(65907),l=e([i,s,a]);async function p(e,{params:t}){try{let r=await (0,s.nc)();if("error"in r)return r.error;let n=r.ctx,{id:l}=await t,p=Number.parseInt(l,10);if(!Number.isInteger(p))return o.NextResponse.json({error:"Nieprawidłowy numer oferty"},{status:400});let f=await e.json().catch(()=>({})),E=f.decision;if(!u.RX.includes(E))return o.NextResponse.json({error:"Nieprawidłowa decyzja klienta"},{status:400});let _="string"==typeof f.note?f.note.trim():"",N="pending"===E||0===_.length?null:_.slice(0,500);if("lost"===E&&void 0!==f.reason&&null!==f.reason&&""!==f.reason&&!(0,d.rJ)(f.reason))return o.NextResponse.json({error:"Nieprawidłowy pow\xf3d odrzucenia"},{status:400});let w="lost"!==E?null:(0,d.rJ)(f.reason)?f.reason:d.Sw,m=await (0,a.Ez)(n,p);if(!m)return o.NextResponse.json({error:"Offer not found"},{status:404});if("sent"===m.offer.status&&!m.actions.canRecordDecision)return(0,c.a)("cannot_decide");let y=[p,E,n.userId,N,w],x=await i.Z.query(`UPDATE offers o
       SET client_decision = $2::text,
           client_decision_at = CASE WHEN $2::text = 'pending' THEN NULL ELSE CURRENT_TIMESTAMP END,
           client_decision_by = CASE WHEN $2::text = 'pending' THEN NULL ELSE $3::int END,
           client_decision_note = CASE WHEN $2::text = 'pending' THEN NULL ELSE $4::text END,
           client_decision_reason = CASE WHEN $2::text = 'lost' THEN $5::text ELSE NULL END,
           updated_at = CURRENT_TIMESTAMP
       WHERE o.id = $1 AND o.status = 'sent'
       RETURNING o.id, o.client_decision, o.client_decision_at, o.client_decision_note,
                 o.client_decision_reason`,y);if(0===x.rows.length)return o.NextResponse.json({error:"Decyzję klienta można zapisać tylko na ofercie wysłanej do klienta"},{status:409});return o.NextResponse.json({offer:x.rows[0]})}catch(e){return console.error("Error recording client decision:",e),o.NextResponse.json({error:"Failed to record client decision"},{status:500})}}[i,s,a]=l.then?(await l)():l,n()}catch(e){n(e)}})},84385:(e,t,r)=>{r.a(e,async(e,n)=>{try{r.d(t,{Ez:()=>d,bJ:()=>c,pP:()=>u});var o=r(9487),i=r(36732),s=r(83173),a=e([o,s]);async function c(e,t,r=o.Z,n=!1){if(!Number.isInteger(t)||t<=0)return null;let s=[t],a=(0,i.ar)(e,s,"o");return(await r.query(`SELECT o.* FROM offers o WHERE o.id = $1 AND ${a} ${n?"FOR UPDATE OF o":""}`,s)).rows[0]??null}async function u(e,t,r=o.Z){let n=await (0,s._o)(t.id,r),i="sent"===t.status?null:await (0,s.y)({flowId:t.flow_id,ownerId:t.user_id,offerData:t.offer_data},r),a=await r.query(`SELECT NOT EXISTS (
       SELECT 1 FROM offers n
       WHERE COALESCE(n.root_offer_id, n.id) = COALESCE($2::int, $1::int) AND n.version_number > $3
     ) AS is_latest`,[t.id,t.root_offer_id,t.version_number]),c=(0,s.un)(e,{userId:t.user_id,flowId:t.flow_id,status:t.status,isLatest:!0===a.rows[0].is_latest,clientDecision:t.client_decision},n,i?.plan??null);return{offer:t,steps:n,assessment:i,actions:c}}async function d(e,t,r=o.Z,n=!1){let i=await c(e,t,r,n);return i?u(e,i,r):null}[o,s]=a.then?(await a)():a,n()}catch(e){n(e)}})},76705:(e,t,r)=>{r.d(t,{LU:()=>n,R9:()=>i,RX:()=>o,Vc:()=>p,_A:()=>d,dV:()=>E,l6:()=>c,lA:()=>s,m$:()=>a,tc:()=>_,up:()=>f,wV:()=>u});let n=["draft","pending_review","approved","rejected","sent"],o=["pending","won","lost"],i=["created","sent","decided"],s=["day","week","month","quarter","year"],a=["steelType","status","decision","salesperson","client"],c=["PICKLED","HRS","TEARDROP","CR","HDG","ZM"],u=7,d="__other__",l=/^\d{4}-\d{2}-\d{2}$/;function p(e){return"string"==typeof e&&l.test(e)&&!Number.isNaN(Date.parse(e))}function f(e,t){if(!e)return[];let r=new Set(t);return Array.from(new Set(e.split(",").map(e=>e.trim()).filter(e=>r.has(e))))}function E(e,t,r){return t.includes(e??"")?e:r}function _(e){return e?Array.from(new Set(e.split(",").map(e=>Number.parseInt(e.trim(),10)).filter(e=>Number.isInteger(e)&&e>0))):[]}},65907:(e,t,r)=>{r.d(t,{Sw:()=>o,Uo:()=>n,rJ:()=>i});let n=["price","lead_time","competitor","project_cancelled","no_response","payment_terms","other"],o="other";function i(e){return"string"==typeof e&&n.includes(e)}}};var t=require("../../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),n=t.X(0,[9276,5972,2015,727,5679],()=>r(4335));module.exports=n})();