"use strict";(()=>{var e={};e.id=4003,e.ids=[4003],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},21764:e=>{e.exports=require("util")},8678:e=>{e.exports=import("pg")},17989:(e,r,i)=>{i.a(e,async(e,t)=>{try{i.r(r),i.d(r,{originalPathname:()=>p,patchFetch:()=>u,requestAsyncStorage:()=>m,routeModule:()=>d,serverHooks:()=>_,staticGenerationAsyncStorage:()=>c});var s=i(49303),a=i(88716),o=i(60670),n=i(58717),l=e([n]);n=(l.then?(await l)():l)[0];let d=new s.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/api/admin/access/route",pathname:"/api/admin/access",filename:"route",bundlePath:"app/api/admin/access/route"},resolvedPagePath:"C:\\Users\\mmazur\\source\\repos\\AMSteel_Quote\\finance_calculator_deployed\\nextjs_space\\app\\api\\admin\\access\\route.ts",nextConfigOutput:"",userland:n}),{requestAsyncStorage:m,staticGenerationAsyncStorage:c,serverHooks:_}=d,p="/api/admin/access/route";function u(){return(0,o.patchFetch)({serverHooks:_,staticGenerationAsyncStorage:c})}t()}catch(e){t(e)}})},58717:(e,r,i)=>{i.a(e,async(e,t)=>{try{i.r(r),i.d(r,{GET:()=>l,dynamic:()=>u});var s=i(87070),a=i(60727),o=i(73630),n=e([a,o]);[a,o]=n.then?(await n)():n;let u="force-dynamic";async function l(){let e=await (0,a.kp)();if("error"in e)return e.error;try{return s.NextResponse.json(await (0,o.E)())}catch(e){return console.error("Error loading access configuration:",e),s.NextResponse.json({error:"Failed to load access configuration"},{status:500})}}t()}catch(e){t(e)}})},73630:(e,r,i)=>{i.a(e,async(e,t)=>{try{i.d(r,{E:()=>n});var s=i(9487),a=i(98562),o=e([s,a]);async function n(e=s.Z){let[r,i,t,o]=await Promise.all([(0,a.fw)(e),(0,a.F3)(e),(0,a.Dx)(e),(0,a.dL)(e)]),n=await e.query("SELECT id, code, name, is_active FROM roles ORDER BY name, id"),l=await e.query(`SELECT fr.*, v.flow_id IS NOT NULL AS has_visibility,
            v.see_own, v.see_team, v.see_branch, v.see_region, v.see_all_in_flow,
            v.see_all_flows, v.see_awaiting_my_review, COALESCE(v.note, '') AS visibility_note,
            (SELECT COUNT(*)::int FROM user_flow_roles m
              WHERE m.flow_id = fr.flow_id AND m.role_id = fr.role_id) AS member_count
     FROM flow_roles fr
     LEFT JOIN visibility_rules v ON v.flow_id = fr.flow_id AND v.role_id = fr.role_id
     ORDER BY fr.flow_id, fr.role_id`),u=await e.query(`SELECT u.id, u.email, COALESCE(NULLIF(TRIM(u.full_name), ''), u.email) AS name,
            u.is_active, u.is_superuser,
            COALESCE((SELECT json_agg(json_build_object('flowId', m.flow_id, 'roleId', m.role_id))
                      FROM user_flow_roles m WHERE m.user_id = u.id), '[]'::json) AS memberships,
            COALESCE((SELECT array_agg(tm.senior_id) FROM team_members tm WHERE tm.junior_id = u.id),
                     '{}') AS leader_ids
     FROM users u
     ORDER BY u.is_active DESC, name`);return{levels:r,flows:i,rules:t,policies:o,roles:n.rows.map(e=>({id:Number(e.id),code:String(e.code),name:String(e.name),isActive:!0===e.is_active})),flowRoles:l.rows.map(e=>({flowId:Number(e.flow_id),roleId:Number(e.role_id),levelId:Number(e.level_id),permissions:(0,a.$i)(e),visibility:e.has_visibility?(0,a.mn)(e):null,visibilityNote:String(e.visibility_note??""),memberCount:Number(e.member_count??0)})),users:u.rows.map(e=>({id:Number(e.id),email:String(e.email),name:String(e.name),isActive:!0===e.is_active,isSuperuser:!0===e.is_superuser,memberships:e.memberships.map(e=>({flowId:Number(e.flowId),roleId:Number(e.roleId)})),leaderIds:e.leader_ids.map(Number)}))}}[s,a]=o.then?(await o)():o,t()}catch(e){t(e)}})}};var r=require("../../../../webpack-runtime.js");r.C(e);var i=e=>r(r.s=e),t=r.X(0,[9276,5972,2015,727],()=>i(17989));module.exports=t})();