"use strict";(()=>{var e={};e.id=143,e.ids=[143],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},21764:e=>{e.exports=require("util")},8678:e=>{e.exports=import("pg")},49557:(e,t,r)=>{r.a(e,async(e,a)=>{try{r.r(t),r.d(t,{originalPathname:()=>w,patchFetch:()=>c,requestAsyncStorage:()=>f,routeModule:()=>d,serverHooks:()=>l,staticGenerationAsyncStorage:()=>p});var s=r(49303),i=r(88716),n=r(60670),o=r(37887),u=e([o]);o=(u.then?(await u)():u)[0];let d=new s.AppRouteRouteModule({definition:{kind:i.x.APP_ROUTE,page:"/api/offers/[id]/reject/route",pathname:"/api/offers/[id]/reject",filename:"route",bundlePath:"app/api/offers/[id]/reject/route"},resolvedPagePath:"C:\\Users\\mmazur\\source\\repos\\AMSteel_Quote\\finance_calculator_deployed\\nextjs_space\\app\\api\\offers\\[id]\\reject\\route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:f,staticGenerationAsyncStorage:p,serverHooks:l}=d,w="/api/offers/[id]/reject/route";function c(){return(0,n.patchFetch)({serverHooks:l,staticGenerationAsyncStorage:p})}a()}catch(e){a(e)}})},37887:(e,t,r)=>{r.a(e,async(e,a)=>{try{r.r(t),r.d(t,{POST:()=>f});var s=r(87070),i=r(9487),n=r(60727),o=r(84385),u=r(83173),c=r(33359),d=e([i,n,o,u]);async function f(e,{params:t}){try{let r=await (0,n.nc)();if("error"in r)return r.error;let{ctx:a}=r,{id:d}=await t,{reason:f}=await e.json().catch(()=>({}));if(!f||"string"!=typeof f||0===f.trim().length)return s.NextResponse.json({error:"Pow\xf3d odrzucenia jest wymagany"},{status:400});let p=await i.Z.connect();try{await p.query("BEGIN");let e=await (0,o.bJ)(a,Number.parseInt(d,10),p,!0);if(!e)return await p.query("ROLLBACK"),s.NextResponse.json({error:"Offer not found"},{status:404});if("pending_review"!==e.status)return await p.query("ROLLBACK"),s.NextResponse.json({error:"Oferta nie jest w statusie oczekującym na weryfikację"},{status:409});let t=(0,u.Nt)(a,await (0,u._o)(e.id,p),e.flow_id,e.user_id);if(0===t.length)return await p.query("ROLLBACK"),(0,c.a)("cannot_review");await p.query(`UPDATE offer_approval_steps
         SET status = 'rejected', decided_by = $2, decided_at = CURRENT_TIMESTAMP, comment = $3
         WHERE id = ANY($1::int[])`,[t.map(e=>e.id),a.userId,f.trim()]),await p.query("UPDATE offer_approval_steps SET status = 'superseded' WHERE offer_id = $1 AND status = 'pending'",[e.id]);let r=await p.query(`UPDATE offers
         SET status = 'rejected', reviewed_by = $2, reviewed_at = CURRENT_TIMESTAMP,
             rejection_reason = $3, updated_at = CURRENT_TIMESTAMP
         WHERE id = $1
         RETURNING id, status, reviewed_by, reviewed_at, rejection_reason`,[e.id,a.userId,f.trim()]);return await p.query("COMMIT"),s.NextResponse.json({offer:r.rows[0]})}catch(e){throw await p.query("ROLLBACK").catch(()=>void 0),e}finally{p.release()}}catch(e){return console.error("Error rejecting offer:",e),s.NextResponse.json({error:"Failed to reject offer"},{status:500})}}[i,n,o,u]=d.then?(await d)():d,a()}catch(e){a(e)}})},84385:(e,t,r)=>{r.a(e,async(e,a)=>{try{r.d(t,{Ez:()=>d,bJ:()=>u,pP:()=>c});var s=r(9487),i=r(36732),n=r(83173),o=e([s,n]);async function u(e,t,r=s.Z,a=!1){if(!Number.isInteger(t)||t<=0)return null;let n=[t],o=(0,i.ar)(e,n,"o");return(await r.query(`SELECT o.* FROM offers o WHERE o.id = $1 AND ${o} ${a?"FOR UPDATE OF o":""}`,n)).rows[0]??null}async function c(e,t,r=s.Z){let a=await (0,n._o)(t.id,r),i="sent"===t.status?null:await (0,n.y)({flowId:t.flow_id,ownerId:t.user_id,offerData:t.offer_data},r),o=await r.query(`SELECT NOT EXISTS (
       SELECT 1 FROM offers n
       WHERE COALESCE(n.root_offer_id, n.id) = COALESCE($2::int, $1::int) AND n.version_number > $3
     ) AS is_latest`,[t.id,t.root_offer_id,t.version_number]),u=(0,n.un)(e,{userId:t.user_id,flowId:t.flow_id,status:t.status,isLatest:!0===o.rows[0].is_latest,clientDecision:t.client_decision},a,i?.plan??null);return{offer:t,steps:a,assessment:i,actions:u}}async function d(e,t,r=s.Z,a=!1){let i=await u(e,t,r,a);return i?c(e,i,r):null}[s,n]=o.then?(await o)():o,a()}catch(e){a(e)}})}};var t=require("../../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[9276,5972,2015,727,5679],()=>r(49557));module.exports=a})();