"use strict";(()=>{var e={};e.id=7023,e.ids=[7023],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},21764:e=>{e.exports=require("util")},8678:e=>{e.exports=import("pg")},3399:(e,r,s)=>{s.a(e,async(e,t)=>{try{s.r(r),s.d(r,{originalPathname:()=>_,patchFetch:()=>l,requestAsyncStorage:()=>u,routeModule:()=>d,serverHooks:()=>c,staticGenerationAsyncStorage:()=>f});var o=s(49303),i=s(88716),n=s(60670),a=s(6675),p=e([a]);a=(p.then?(await p)():p)[0];let d=new o.AppRouteRouteModule({definition:{kind:i.x.APP_ROUTE,page:"/api/senior/offers/route",pathname:"/api/senior/offers",filename:"route",bundlePath:"app/api/senior/offers/route"},resolvedPagePath:"C:\\Users\\mmazur\\source\\repos\\AMSteel_Quote\\finance_calculator_deployed\\nextjs_space\\app\\api\\senior\\offers\\route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:u,staticGenerationAsyncStorage:f,serverHooks:c}=d,_="/api/senior/offers/route";function l(){return(0,n.patchFetch)({serverHooks:c,staticGenerationAsyncStorage:f})}t()}catch(e){t(e)}})},6675:(e,r,s)=>{s.a(e,async(e,t)=>{try{s.r(r),s.d(r,{GET:()=>d,dynamic:()=>u});var o=s(87070),i=s(9487),n=s(60727),a=s(36732),p=s(67785),l=e([i,n]);[i,n]=l.then?(await l)():l;let u="force-dynamic",f=`o.id, o.offer_name, o.display_name, o.offer_data, o.status, o.user_id,
  o.created_at, o.updated_at, o.reviewed_by, o.reviewed_at, o.rejection_reason, o.sent_at,
  o.root_offer_id, o.version_number,
  u.full_name AS owner_name, u.email AS owner_email,
  r.full_name AS reviewer_name, f.name AS flow_name, o.validation_snapshot,
  ARRAY(SELECT l.code FROM offer_approval_steps ps JOIN hierarchy_levels l ON l.id = ps.level_id
        WHERE ps.offer_id = o.id AND ps.status = 'pending' ORDER BY ps.id) AS pending_levels`,c=`(
  o.display_name ILIKE '%' || $2 || '%'
  OR o.id::text = $2
  OR o.offer_data->'clientInfo'->>'company' ILIKE '%' || $2 || '%'
  OR o.offer_data->'clientInfo'->>'sapId' ILIKE '%' || $2 || '%'
)`;async function d(e){try{let r=await (0,n.nc)();if("error"in r)return r.error;let s=r.ctx;if(!(0,n.aI)(s))return(0,n.ID)();let t=(e.nextUrl.searchParams.get("q")||"").trim(),l=[s.userId,t?(0,p.p)(t):null],d=(0,a.ew)(s,l,"o"),u=`(${d} OR (o.reviewed_by = $1 OR EXISTS (SELECT 1 FROM offer_approval_steps hs WHERE hs.offer_id = o.id AND hs.decided_by = $1)))`,_=`${u} AND ($2::text IS NULL OR ${c})`,h=await i.Z.query(`SELECT ${f}, ${d} AS awaiting_me
       FROM offers o
       LEFT JOIN users u ON u.id = o.user_id
       LEFT JOIN users r ON r.id = o.reviewed_by
       LEFT JOIN flows f ON f.id = o.flow_id
       WHERE ${_}
       ORDER BY
         CASE WHEN ${d} THEN 0 ELSE 1 END,
         o.updated_at DESC`,l);return o.NextResponse.json({offers:h.rows,userId:s.userId})}catch(e){return console.error("Error fetching senior offers:",e),o.NextResponse.json({error:"Failed to fetch offers"},{status:500})}}t()}catch(e){t(e)}})},36732:(e,r,s)=>{function t(e,r,s="o"){if(e.isSuperuser||e.memberships.some(e=>e.visibility.seeAllFlows))return"TRUE";r.push(e.userId);let t=`$${r.length}`,o=[`${s}.user_id = ${t}`],i=e.memberships.filter(e=>e.permissions.canApproveReject).map(e=>e.flowId);for(let n of(i.length>0&&(r.push(i),o.push(`(${s}.flow_id = ANY($${r.length}::int[]) AND EXISTS (SELECT 1 FROM offer_approval_steps hs WHERE hs.offer_id = ${s}.id AND hs.decided_by = ${t}))`)),e.memberships)){let t=n.visibility,i=null,a=()=>(null===i&&(r.push(n.flowId),i=`$${r.length}`),i),p="flow"===e.orgScopeFallback&&(t.seeBranch||t.seeRegion);if(t.seeAllInFlow||p)o.push(`${s}.flow_id = ${a()}`);else if((t.seeTeam||t.seeBranch||t.seeRegion)&&e.teamUserIds.length>0){let t=a();r.push(e.teamUserIds),o.push(`(${s}.flow_id = ${t} AND ${s}.user_id = ANY($${r.length}::int[]))`)}if(t.seeAwaitingMyReview&&n.permissions.canApproveReject){let e=a();r.push(n.level.id),o.push(`(${s}.flow_id = ${e} AND EXISTS (SELECT 1 FROM offer_approval_steps qs WHERE qs.offer_id = ${s}.id AND qs.status = 'pending' AND qs.level_id = $${r.length}))`)}}return`(${o.join(" OR ")})`}function o(e,r,s="o"){let t=[];if(e.isSuperuser)t.push(`EXISTS (SELECT 1 FROM offer_approval_steps aq WHERE aq.offer_id = ${s}.id AND aq.status = 'pending')`);else for(let o of e.memberships){if(!o.permissions.canApproveReject)continue;r.push(o.flowId);let e=`$${r.length}`;r.push(o.level.id),t.push(`(${s}.flow_id = ${e} AND EXISTS (SELECT 1 FROM offer_approval_steps aq WHERE aq.offer_id = ${s}.id AND aq.status = 'pending' AND aq.level_id = $${r.length}))`)}return 0===t.length?"FALSE":(r.push(e.userId),`((${t.join(" OR ")}) AND ${s}.user_id IS DISTINCT FROM $${r.length})`)}s.d(r,{ar:()=>t,ew:()=>o})},67785:(e,r,s)=>{s.d(r,{p:()=>t});function t(e){return e.replace(/[\\%_]/g,e=>`\\${e}`)}}};var r=require("../../../../webpack-runtime.js");r.C(e);var s=e=>r(r.s=e),t=r.X(0,[9276,5972,2015,727],()=>s(3399));module.exports=t})();