"use strict";(()=>{var e={};e.id=3471,e.ids=[3471],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},21764:e=>{e.exports=require("util")},8678:e=>{e.exports=import("pg")},47394:(e,t,r)=>{r.a(e,async(e,n)=>{try{r.r(t),r.d(t,{originalPathname:()=>m,patchFetch:()=>u,requestAsyncStorage:()=>d,routeModule:()=>f,serverHooks:()=>p,staticGenerationAsyncStorage:()=>c});var a=r(49303),i=r(88716),s=r(60670),o=r(43442),l=e([o]);o=(l.then?(await l)():l)[0];let f=new a.AppRouteRouteModule({definition:{kind:i.x.APP_ROUTE,page:"/api/offers/[id]/route",pathname:"/api/offers/[id]",filename:"route",bundlePath:"app/api/offers/[id]/route"},resolvedPagePath:"C:\\Users\\mmazur\\source\\repos\\AMSteel_Quote\\finance_calculator_deployed\\nextjs_space\\app\\api\\offers\\[id]\\route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:d,staticGenerationAsyncStorage:c,serverHooks:p}=f,m="/api/offers/[id]/route";function u(){return(0,s.patchFetch)({serverHooks:p,staticGenerationAsyncStorage:c})}n()}catch(e){n(e)}})},43442:(e,t,r)=>{r.a(e,async(e,n)=>{try{r.r(t),r.d(t,{DELETE:()=>w,GET:()=>_,PUT:()=>y});var a=r(87070),i=r(9487),s=r(69319),o=r(26409),l=r(60727),u=r(84385),f=r(83173),d=r(31114),c=r(98562),p=r(33359),m=r(49947),E=e([i,l,u,f,c,m]);async function _(e,{params:t}){try{let e=await (0,l.nc)();if("error"in e)return e.error;let{ctx:r}=e,{id:n}=await t,s=await (0,u.Ez)(r,Number.parseInt(n,10));if(!s)return a.NextResponse.json({error:"Offer not found"},{status:404});let o=await i.Z.query(`SELECT u.full_name AS owner_name, u.email AS owner_email, f.name AS flow_name
       FROM offers o LEFT JOIN users u ON u.id = o.user_id LEFT JOIN flows f ON f.id = o.flow_id
       WHERE o.id = $1`,[s.offer.id]);return a.NextResponse.json({offer:{...s.offer,...o.rows[0],can_review:s.actions.canReview,actions:s.actions,steps:s.steps,validation:s.assessment?(0,f.PS)(s.assessment):s.offer.validation_snapshot??null}})}catch(e){return console.error("Error fetching offer:",e),a.NextResponse.json({error:"Failed to fetch offer"},{status:500})}}async function y(e,{params:t}){try{let r;let n=await (0,l.nc)();if("error"in n)return n.error;let{ctx:s}=n,{id:o}=await t,u=Number.parseInt(o,10),{offer_name:f,offer_data:d}=await e.json().catch(()=>null)??{};if(!d||"object"!=typeof d||!Number.isInteger(u))return a.NextResponse.json({error:"Missing required fields"},{status:400});let c=(0,m.n)(d);if(c)return a.NextResponse.json({error:c},{status:400});let p="string"==typeof f&&f.trim()?f.trim():null,E=await i.Z.connect();try{await E.query("BEGIN"),r=await R(E,s,u,p,d),await E.query("ok"===r.kind?"COMMIT":"ROLLBACK")}catch(e){throw await E.query("ROLLBACK").catch(()=>void 0),e}finally{E.release()}if("error"===r.kind)return r.response;return a.NextResponse.json({offer:r.row})}catch(e){return console.error("Error updating offer:",e),a.NextResponse.json({error:"Failed to update offer"},{status:500})}}async function R(e,t,r,n,i){let l=await (0,u.bJ)(t,r,e,!0);if(!l)return{kind:"error",response:a.NextResponse.json({error:"Offer not found"},{status:404})};let{actions:m}=await (0,u.pP)(t,l,e);if("sent"===l.status&&!m.canEdit)return{kind:"error",response:a.NextResponse.json({error:"Oferta została wysłana do klienta i jest tylko do odczytu"},{status:409})};if(!m.canEdit)return{kind:"error",response:(0,p.a)("cannot_edit")};let E=t.memberships.find(e=>e.flowId===l.flow_id)?.permissions,_=(0,d.G)(t.isSuperuser||!E?"all":E,i,l.offer_data,await (0,c.bC)(i.validFrom,e),await (0,c.xE)(e));if(_)return{kind:"error",response:(0,p.a)(_)};let y=(0,o.MM)(i.clientInfo),R=await (0,s.LM)(e,y,t.userId),w=l.offer_name===n&&function e(t,r){if(t===r)return!0;if("object"!=typeof t||"object"!=typeof r||null===t||null===r||Array.isArray(t)!==Array.isArray(r))return!1;if(Array.isArray(t)&&Array.isArray(r))return t.length===r.length&&t.every((t,n)=>e(t,r[n]));let n=Object.keys(t),a=Object.keys(r);return n.length===a.length&&n.every(n=>Object.prototype.hasOwnProperty.call(r,n)&&e(t[n],r[n]))}(l.offer_data,i);if(w&&"sent"===l.status)return{kind:"ok",row:l};if(w){let t=await e.query(`UPDATE offers
       SET offer_name = $1, offer_data = $2, client_id = $3, updated_at = CURRENT_TIMESTAMP
       WHERE id = $4
       RETURNING id, offer_name, display_name, offer_data, status, flow_id, created_at, updated_at,
                 root_offer_id, version_number`,[n,JSON.stringify(i),R,r]);return{kind:"ok",row:t.rows[0]}}let N=l.root_offer_id??l.id;await e.query("SELECT pg_advisory_xact_lock(hashtext('offer_family'), $1)",[N]);let L=await e.query("SELECT version_number FROM offers WHERE id = $1 OR root_offer_id = $1 FOR UPDATE",[N]),I=Math.max(0,...L.rows.map(e=>Number(e.version_number)))+1,T=await (0,f.y)({flowId:l.flow_id,ownerId:l.user_id,offerData:i},e),$="sent"===l.status?"draft":l.status;if("pending_review"===l.status||"approved"===l.status){if(T.plan.blocked)return{kind:"error",response:(0,p.a)("level_conflict",{validation:(0,f.PS)(T)})};$=(0,f.OR)(T.plan)?"pending_review":"approved"}let h=(await e.query(`INSERT INTO offers (user_id, offer_name, offer_data, client_id, status, root_offer_id,
                         version_number, flow_id, validation_snapshot)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
     RETURNING id, offer_name, display_name, offer_data, status, flow_id, created_at, updated_at,
               root_offer_id, version_number`,[l.user_id,n,JSON.stringify(i),R,$,N,I,l.flow_id,JSON.stringify((0,f.PS)(T))])).rows[0];return"pending_review"===$&&await (0,f.NJ)(h.id,T.plan,e),await e.query("UPDATE offer_approval_steps SET status = 'superseded' WHERE offer_id = $1 AND status = 'pending'",[l.id]),{kind:"ok",row:h}}async function w(e,{params:t}){try{let e=await (0,l.nc)();if("error"in e)return e.error;let r=e.ctx,{id:n}=await t,s=Number.parseInt(n,10);if(!Number.isInteger(s))return a.NextResponse.json({error:"Offer not found"},{status:404});let o=await i.Z.query("DELETE FROM offers WHERE id = $1 AND user_id = $2 AND status IN ('draft', 'rejected') RETURNING id",[s,r.userId]);if(0===o.rows.length){if((await i.Z.query("SELECT status FROM offers WHERE id = $1 AND user_id = $2",[s,r.userId])).rows.length>0)return a.NextResponse.json({error:"Usunąć można tylko szkic lub odrzuconą ofertę"},{status:409});return a.NextResponse.json({error:"Offer not found"},{status:404})}return a.NextResponse.json({success:!0})}catch(e){return console.error("Error deleting offer:",e),a.NextResponse.json({error:"Failed to delete offer"},{status:500})}}[i,l,u,f,c,m]=E.then?(await E)():E,n()}catch(e){n(e)}})},31114:(e,t,r)=>{function n(e){let t=e?.zestawienie;return Array.isArray(t)?t:[]}r.d(t,{G:()=>s});let a=(e,t)=>1e-6>=Math.abs(e-t);function i(e){if("number"==typeof e)return Number.isFinite(e)?e:null;if("string"==typeof e&&""!==e.trim()){let t=Number(e);return Number.isFinite(t)?t:null}return null}function s(e,t,r,s,o){if("all"===e)return null;let l=n(r);for(let[r,u]of n(t).entries()){let t=function(e,t,r){if(void 0!==t.id&&null!==t.id){let r=e.find(e=>e.id===t.id);if(r)return r}return e[r]}(l,u,r);if(!e.canChangePglBase){let e=i(u.pgl);if(null===e)return"pgl_locked";let r="string"==typeof u.type?s(u.type):Number.NaN,n=i(t?.pgl);if(!a(e,r)&&!(null!==n&&a(n,e)))return"pgl_locked"}let n=u.inputs?.marginPct;if(!e.canChangePriceMargin&&void 0!==n){let e=i(n),r=i(t?.inputs?.marginPct);if(!(null!==e&&(a(e,o)||null!==r&&a(r,e))))return"margin_locked"}}return null}},84385:(e,t,r)=>{r.a(e,async(e,n)=>{try{r.d(t,{Ez:()=>f,bJ:()=>l,pP:()=>u});var a=r(9487),i=r(36732),s=r(83173),o=e([a,s]);async function l(e,t,r=a.Z,n=!1){if(!Number.isInteger(t)||t<=0)return null;let s=[t],o=(0,i.ar)(e,s,"o");return(await r.query(`SELECT o.* FROM offers o WHERE o.id = $1 AND ${o} ${n?"FOR UPDATE OF o":""}`,s)).rows[0]??null}async function u(e,t,r=a.Z){let n=await (0,s._o)(t.id,r),i="sent"===t.status?null:await (0,s.y)({flowId:t.flow_id,ownerId:t.user_id,offerData:t.offer_data},r),o=await r.query(`SELECT NOT EXISTS (
       SELECT 1 FROM offers n
       WHERE COALESCE(n.root_offer_id, n.id) = COALESCE($2::int, $1::int) AND n.version_number > $3
     ) AS is_latest`,[t.id,t.root_offer_id,t.version_number]),l=(0,s.un)(e,{userId:t.user_id,flowId:t.flow_id,status:t.status,isLatest:!0===o.rows[0].is_latest,clientDecision:t.client_decision},n,i?.plan??null);return{offer:t,steps:n,assessment:i,actions:l}}async function f(e,t,r=a.Z,n=!1){let i=await l(e,t,r,n);return i?u(e,i,r):null}[a,s]=o.then?(await o)():o,n()}catch(e){n(e)}})},69319:(e,t,r)=>{async function n(e,t,r){if(""!==r){let t=await e.query("SELECT id FROM clients WHERE LOWER(TRIM(nip)) = LOWER($1) ORDER BY id ASC LIMIT 1",[r]);if(t.rows.length>0)return t.rows[0].id}let n=await e.query("SELECT id FROM clients WHERE LOWER(TRIM(company)) = LOWER($1) ORDER BY id ASC LIMIT 1",[t]);return n.rows.length>0?n.rows[0].id:null}async function a(e,t,r,n){let a=r.firstName.trim(),i=r.lastName.trim();if(""===a&&""===i)return;let s=r.phone.trim(),o=r.email.trim(),l=await e.query(`SELECT id FROM client_contacts
     WHERE client_id = $1
       AND LOWER(TRIM(COALESCE(first_name, ''))) = LOWER($2)
       AND LOWER(TRIM(COALESCE(last_name,  ''))) = LOWER($3)
     ORDER BY id ASC
     LIMIT 1`,[t,a,i]);if(0===l.rows.length){await e.query(`INSERT INTO client_contacts (client_id, first_name, last_name, phone, email, created_by)
       VALUES ($1, $2, $3, $4, $5, $6)`,[t,a||null,i||null,s||null,o||null,n]);return}await e.query(`UPDATE client_contacts
     SET phone      = COALESCE(NULLIF(TRIM(phone), ''), $1),
         email      = COALESCE(NULLIF(TRIM(email), ''), $2),
         updated_at = CURRENT_TIMESTAMP
     WHERE id = $3`,[s||null,o||null,l.rows[0].id])}async function i(e,t,r,n){let a=r.firstName.trim(),i=r.lastName.trim();if(""===a&&""===i)return;let s=r.phone.trim(),o=r.email.trim(),l=await e.query(`SELECT id FROM client_contacts
     WHERE client_id = $1
       AND LOWER(TRIM(COALESCE(first_name, ''))) = LOWER($2)
       AND LOWER(TRIM(COALESCE(last_name,  ''))) = LOWER($3)
     ORDER BY id ASC
     LIMIT 1`,[t,a,i]);if(0===l.rows.length){await e.query(`INSERT INTO client_contacts (client_id, first_name, last_name, phone, email, created_by)
       VALUES ($1, $2, $3, $4, $5, $6)`,[t,a||null,i||null,s||null,o||null,n]);return}await e.query(`UPDATE client_contacts
     SET phone      = $1,
         email      = $2,
         updated_at = CURRENT_TIMESTAMP
     WHERE id = $3`,[s||null,o||null,l.rows[0].id])}async function s(e,t,r){let i=t.company.trim(),s=t.nip.trim();if(""===i)return null;let o=t.address.trim(),l=t.sapId.trim(),u=t.firstName.trim(),f=t.lastName.trim(),d=t.phone.trim(),c=t.email.trim(),p=await n(e,i,s);if(null===p){let n=(await e.query(`INSERT INTO clients (company, nip, address, sap_id, first_name, last_name, phone, email, created_by)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       RETURNING id`,[i,s||null,o||null,l||null,u||null,f||null,d||null,c||null,r])).rows[0].id;return await a(e,n,t,r),n}return await e.query(`UPDATE clients
     SET company    = COALESCE(NULLIF(TRIM(company),    ''), $1),
         nip        = COALESCE(NULLIF(TRIM(nip),        ''), $2),
         address    = COALESCE(NULLIF(TRIM(address),    ''), $3),
         sap_id     = COALESCE(NULLIF(TRIM(sap_id),     ''), $4),
         first_name = COALESCE(NULLIF(TRIM(first_name), ''), $5),
         last_name  = COALESCE(NULLIF(TRIM(last_name),  ''), $6),
         phone      = COALESCE(NULLIF(TRIM(phone),      ''), $7),
         email      = COALESCE(NULLIF(TRIM(email),      ''), $8),
         updated_at = CURRENT_TIMESTAMP
     WHERE id = $9`,[i,s||null,o||null,l||null,u||null,f||null,d||null,c||null,p]),await a(e,p,t,r),p}r.d(t,{LM:()=>s,r8:()=>n,tS:()=>i})},49947:(e,t,r)=>{r.a(e,async(e,n)=>{try{r.d(t,{n:()=>o});var a=r(7410),i=r(54755),s=e([i]);i=(s.then?(await s)():s)[0];let l=a.z.number().finite(),u=l.positive(),f=a.z.object({type:a.z.enum(i.My),grade:a.z.string().trim().min(1),thickness:u,width:u,length:l.nonnegative(),isCoil:a.z.boolean().optional(),tons:u,pgl:u,sumaHuta:l,sumaSSC:l,marza:l,finalPrice:u,totalValue:u,inputs:a.z.object({marginPct:l,extra:l,transport:l}).passthrough().optional()}).passthrough(),d=(e,t)=>.01>=Math.abs(e-t);function o(e){let t=e.zestawienie;if(void 0===t)return null;if(!Array.isArray(t))return"zestawienie must be an array";for(let e=0;e<t.length;e++){let r=f.safeParse(t[e]);if(!r.success){let t=r.error.issues[0];return`Item ${e+1}: invalid ${t.path.join(".")||"item"} (${t.message})`}let n=function(e){if(!e.isCoil&&e.length<=0)return"length must be > 0 for sheets";if(!d(e.totalValue,Math.round(e.finalPrice*e.tons*100)/100))return"totalValue does not equal finalPrice \xd7 tons";if(!e.inputs)return null;let t=e.pgl+e.sumaHuta;if(!d(e.marza,e.inputs.marginPct/100*t))return"marza does not match (PGL + Σ Mill) \xd7 margin %";let r=t+e.marza+e.inputs.extra+e.inputs.transport+e.sumaSSC;return d(e.finalPrice,r)?null:"finalPrice does not equal PGL + Σ Mill + margin + extra + transport + Σ SSC"}(r.data);if(n)return`Item ${e+1}: ${n}`}return null}n()}catch(e){n(e)}})},26409:(e,t,r)=>{r.d(t,{MM:()=>a,uV:()=>i});let n={company:"",nip:"",address:"",sapId:"",firstName:"",lastName:"",phone:"",email:""};function a(e){if(!e||"object"!=typeof e)return{...n};let t=e=>"string"==typeof e?e:"";return{company:t(e.company),nip:t(e.nip),address:t(e.address),sapId:t(e.sapId),firstName:t(e.firstName),lastName:t(e.lastName),phone:t(e.phone),email:t(e.email)}}function i(e){return""!==e.company.trim()&&""!==e.nip.trim()}}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),n=t.X(0,[9276,5972,2015,7410,727,5679],()=>r(47394));module.exports=n})();