"use strict";(()=>{var e={};e.id=7431,e.ids=[7431],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},21764:e=>{e.exports=require("util")},8678:e=>{e.exports=import("pg")},26588:(e,t,r)=>{r.a(e,async(e,a)=>{try{r.r(t),r.d(t,{originalPathname:()=>w,patchFetch:()=>d,requestAsyncStorage:()=>l,routeModule:()=>p,serverHooks:()=>f,staticGenerationAsyncStorage:()=>c});var i=r(49303),o=r(88716),s=r(60670),n=r(9101),u=e([n]);n=(u.then?(await u)():u)[0];let p=new i.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/offers/[id]/approve/route",pathname:"/api/offers/[id]/approve",filename:"route",bundlePath:"app/api/offers/[id]/approve/route"},resolvedPagePath:"C:\\Users\\mmazur\\source\\repos\\AMSteel_Quote\\finance_calculator_deployed\\nextjs_space\\app\\api\\offers\\[id]\\approve\\route.ts",nextConfigOutput:"",userland:n}),{requestAsyncStorage:l,staticGenerationAsyncStorage:c,serverHooks:f}=p,w="/api/offers/[id]/approve/route";function d(){return(0,s.patchFetch)({serverHooks:f,staticGenerationAsyncStorage:c})}a()}catch(e){a(e)}})},9101:(e,t,r)=>{r.a(e,async(e,a)=>{try{r.r(t),r.d(t,{POST:()=>l});var i=r(87070),o=r(9487),s=r(60727),n=r(84385),u=r(83173),d=r(33359),p=e([o,s,n,u]);async function l(e,{params:t}){try{let r=await (0,s.nc)();if("error"in r)return r.error;let{ctx:a}=r,{id:p}=await t,l=await e.json().catch(()=>({})),c="string"==typeof l.comment&&l.comment.trim()?l.comment.trim().slice(0,1e3):null,f=await o.Z.connect();try{await f.query("BEGIN");let e=await (0,n.bJ)(a,Number.parseInt(p,10),f,!0);if(!e)return await f.query("ROLLBACK"),i.NextResponse.json({error:"Offer not found"},{status:404});if("pending_review"!==e.status)return await f.query("ROLLBACK"),i.NextResponse.json({error:"Oferta nie jest w statusie oczekującym na weryfikację"},{status:409});let t=await (0,u._o)(e.id,f);if(0===(0,u.Nt)(a,t,e.flow_id,e.user_id).length)return await f.query("ROLLBACK"),(0,d.a)("cannot_review");let r=await (0,u.F3)(e,t,f);if("blocked"===r.kind)return await f.query("ROLLBACK"),(0,d.a)("level_conflict",{validation:(0,u.PS)(r.assessment)});if("rerouted"===r.kind)return await f.query("COMMIT"),(0,d.a)("rerouted",{levels:r.levels,validation:(0,u.PS)(r.assessment)});let o=(0,u.Nt)(a,t,e.flow_id,e.user_id);await f.query(`UPDATE offer_approval_steps
         SET status = 'approved', decided_by = $2, decided_at = CURRENT_TIMESTAMP, comment = $3
         WHERE id = ANY($1::int[])`,[o.map(e=>e.id),a.userId,c]);let s=await f.query("SELECT 1 FROM offer_approval_steps WHERE offer_id = $1 AND status = 'pending' LIMIT 1",[e.id]),l=0===s.rows.length,w=await f.query(`UPDATE offers
         SET status = CASE WHEN $3 THEN 'approved' ELSE status END,
             reviewed_by = $2, reviewed_at = CURRENT_TIMESTAMP,
             rejection_reason = NULL, updated_at = CURRENT_TIMESTAMP
         WHERE id = $1
         RETURNING id, status, reviewed_by, reviewed_at`,[e.id,a.userId,l]);return await f.query("COMMIT"),i.NextResponse.json({offer:w.rows[0],fullyApproved:l})}catch(e){throw await f.query("ROLLBACK").catch(()=>void 0),e}finally{f.release()}}catch(e){return console.error("Error approving offer:",e),i.NextResponse.json({error:"Failed to approve offer"},{status:500})}}[o,s,n,u]=p.then?(await p)():p,a()}catch(e){a(e)}})},84385:(e,t,r)=>{r.a(e,async(e,a)=>{try{r.d(t,{Ez:()=>p,bJ:()=>u,pP:()=>d});var i=r(9487),o=r(36732),s=r(83173),n=e([i,s]);async function u(e,t,r=i.Z,a=!1){if(!Number.isInteger(t)||t<=0)return null;let s=[t],n=(0,o.ar)(e,s,"o");return(await r.query(`SELECT o.* FROM offers o WHERE o.id = $1 AND ${n} ${a?"FOR UPDATE OF o":""}`,s)).rows[0]??null}async function d(e,t,r=i.Z){let a=await (0,s._o)(t.id,r),o="sent"===t.status?null:await (0,s.y)({flowId:t.flow_id,ownerId:t.user_id,offerData:t.offer_data},r),n=await r.query(`SELECT NOT EXISTS (
       SELECT 1 FROM offers n
       WHERE COALESCE(n.root_offer_id, n.id) = COALESCE($2::int, $1::int) AND n.version_number > $3
     ) AS is_latest`,[t.id,t.root_offer_id,t.version_number]),u=(0,s.un)(e,{userId:t.user_id,flowId:t.flow_id,status:t.status,isLatest:!0===n.rows[0].is_latest,clientDecision:t.client_decision},a,o?.plan??null);return{offer:t,steps:a,assessment:o,actions:u}}async function p(e,t,r=i.Z,a=!1){let o=await u(e,t,r,a);return o?d(e,o,r):null}[i,s]=n.then?(await n)():n,a()}catch(e){a(e)}})}};var t=require("../../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[9276,5972,2015,727,5679],()=>r(26588));module.exports=a})();