"use strict";(()=>{var e={};e.id=8708,e.ids=[8708],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},21764:e=>{e.exports=require("util")},8678:e=>{e.exports=import("pg")},37832:(e,t,r)=>{r.a(e,async(e,a)=>{try{r.r(t),r.d(t,{originalPathname:()=>E,patchFetch:()=>u,requestAsyncStorage:()=>p,routeModule:()=>c,serverHooks:()=>m,staticGenerationAsyncStorage:()=>d});var n=r(49303),i=r(88716),s=r(60670),l=r(74974),o=e([l]);l=(o.then?(await o)():o)[0];let c=new n.AppRouteRouteModule({definition:{kind:i.x.APP_ROUTE,page:"/api/admin/clients/route",pathname:"/api/admin/clients",filename:"route",bundlePath:"app/api/admin/clients/route"},resolvedPagePath:"C:\\Users\\mmazur\\source\\repos\\AMSteel_Quote\\finance_calculator_deployed\\nextjs_space\\app\\api\\admin\\clients\\route.ts",nextConfigOutput:"",userland:l}),{requestAsyncStorage:p,staticGenerationAsyncStorage:d,serverHooks:m}=c,E="/api/admin/clients/route";function u(){return(0,s.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:d})}a()}catch(e){a(e)}})},74974:(e,t,r)=>{r.a(e,async(e,a)=>{try{r.r(t),r.d(t,{DELETE:()=>d,GET:()=>u,PATCH:()=>p,POST:()=>c});var n=r(87070),i=r(9487),s=r(60727),l=r(69319),o=e([i,s]);async function u(){let e=await (0,s.nc)();if("error"in e)return e.error;if(!(0,s.aI)(e.ctx))return(0,s.ID)();try{let e=await i.Z.query(`SELECT c.id, c.first_name, c.last_name, c.company, c.nip, c.address, c.sap_id,
              c.phone, c.email, c.payment_term_days, c.created_by, c.created_at, c.updated_at,
              COUNT(o.id)::int AS offers_count
       FROM clients c
       LEFT JOIN offers o ON o.client_id = c.id
       GROUP BY c.id
       ORDER BY c.company NULLS LAST, c.last_name NULLS LAST, c.id`);return n.NextResponse.json({clients:e.rows})}catch(e){return console.error("Error fetching clients:",e),n.NextResponse.json({error:"Failed to fetch clients"},{status:500})}}async function c(e){let t=await (0,s.kp)();if("error"in t)return t.error;let r=t.ctx;try{let{first_name:t,last_name:a,company:s,nip:o,address:u,sap_id:c,phone:p,email:d}=await e.json();if(!s&&!a&&!t)return n.NextResponse.json({error:"Podaj przynajmniej firmę lub nazwisko klienta"},{status:400});let m=await i.Z.connect();try{await m.query("BEGIN");let e=(await m.query(`INSERT INTO clients (first_name, last_name, company, nip, address, sap_id, phone, email, created_by)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
         RETURNING id, first_name, last_name, company, nip, address, sap_id, phone, email, created_by, created_at, updated_at`,[t||null,a||null,s||null,o||null,u||null,c||null,p||null,d||null,r.userId])).rows[0];return await (0,l.tS)(m,e.id,{firstName:t||"",lastName:a||"",phone:p||"",email:d||""},r.userId),await m.query("COMMIT"),n.NextResponse.json({client:e},{status:201})}catch(e){throw await m.query("ROLLBACK"),e}finally{m.release()}}catch(e){return console.error("Error creating client:",e),n.NextResponse.json({error:"Failed to create client"},{status:500})}}async function p(e){let t=await (0,s.nc)();if("error"in t)return t.error;if(!(0,s.aI)(t.ctx))return(0,s.ID)();let r=t.ctx;try{let t=await e.json(),{id:a}=t;if(!a)return n.NextResponse.json({error:"Brak id klienta"},{status:400});let s=["first_name","last_name","company","nip","address","sap_id","phone","email"];if(!r.isSuperuser&&s.some(e=>void 0!==t[e]))return n.NextResponse.json({error:"Tylko administrator może zmienić dane klienta poza terminem płatności"},{status:403});let o=[],u=[],c=1;if(r.isSuperuser)for(let e of s)void 0!==t[e]&&(o.push(`${e} = $${c++}`),u.push(t[e]||null));if(void 0!==t.payment_term_days){if(null===t.payment_term_days||""===t.payment_term_days)o.push(`payment_term_days = $${c++}`),u.push(null);else{let e="string"==typeof t.payment_term_days?parseFloat(t.payment_term_days):t.payment_term_days;if("number"!=typeof e||!Number.isFinite(e)||e<0||e>365)return n.NextResponse.json({error:"Termin płatności: podaj liczbę dni 0-365 albo zostaw puste"},{status:400});o.push(`payment_term_days = $${c++}`),u.push(Math.round(e))}}if(0===o.length)return n.NextResponse.json({error:"Brak p\xf3l do zmiany"},{status:400});o.push("updated_at = CURRENT_TIMESTAMP"),u.push(a);let p=await i.Z.connect();try{await p.query("BEGIN");let e=await p.query(`UPDATE clients SET ${o.join(", ")} WHERE id = $${c}
         RETURNING id, first_name, last_name, company, nip, address, sap_id, phone, email, payment_term_days, created_by, created_at, updated_at`,u);if(0===e.rows.length)return await p.query("ROLLBACK"),n.NextResponse.json({error:"Nie znaleziono klienta"},{status:404});let t=e.rows[0];return await (0,l.tS)(p,t.id,{firstName:t.first_name||"",lastName:t.last_name||"",phone:t.phone||"",email:t.email||""},r.userId),await p.query("COMMIT"),n.NextResponse.json({client:t})}catch(e){throw await p.query("ROLLBACK"),e}finally{p.release()}}catch(e){return console.error("Error updating client:",e),n.NextResponse.json({error:"Failed to update client"},{status:500})}}async function d(e){let t=await (0,s.kp)();if("error"in t)return t.error;try{let t=parseInt(e.nextUrl.searchParams.get("id")||"");if(!t)return n.NextResponse.json({error:"Brak id klienta"},{status:400});let r=await i.Z.query("DELETE FROM clients WHERE id = $1 RETURNING id",[t]);if(0===r.rows.length)return n.NextResponse.json({error:"Nie znaleziono klienta"},{status:404});return n.NextResponse.json({success:!0})}catch(e){return console.error("Error deleting client:",e),n.NextResponse.json({error:"Failed to delete client"},{status:500})}}[i,s]=o.then?(await o)():o,a()}catch(e){a(e)}})},69319:(e,t,r)=>{async function a(e,t,r){if(""!==r){let t=await e.query("SELECT id FROM clients WHERE LOWER(TRIM(nip)) = LOWER($1) ORDER BY id ASC LIMIT 1",[r]);if(t.rows.length>0)return t.rows[0].id}let a=await e.query("SELECT id FROM clients WHERE LOWER(TRIM(company)) = LOWER($1) ORDER BY id ASC LIMIT 1",[t]);return a.rows.length>0?a.rows[0].id:null}async function n(e,t,r,a){let n=r.firstName.trim(),i=r.lastName.trim();if(""===n&&""===i)return;let s=r.phone.trim(),l=r.email.trim(),o=await e.query(`SELECT id FROM client_contacts
     WHERE client_id = $1
       AND LOWER(TRIM(COALESCE(first_name, ''))) = LOWER($2)
       AND LOWER(TRIM(COALESCE(last_name,  ''))) = LOWER($3)
     ORDER BY id ASC
     LIMIT 1`,[t,n,i]);if(0===o.rows.length){await e.query(`INSERT INTO client_contacts (client_id, first_name, last_name, phone, email, created_by)
       VALUES ($1, $2, $3, $4, $5, $6)`,[t,n||null,i||null,s||null,l||null,a]);return}await e.query(`UPDATE client_contacts
     SET phone      = COALESCE(NULLIF(TRIM(phone), ''), $1),
         email      = COALESCE(NULLIF(TRIM(email), ''), $2),
         updated_at = CURRENT_TIMESTAMP
     WHERE id = $3`,[s||null,l||null,o.rows[0].id])}async function i(e,t,r,a){let n=r.firstName.trim(),i=r.lastName.trim();if(""===n&&""===i)return;let s=r.phone.trim(),l=r.email.trim(),o=await e.query(`SELECT id FROM client_contacts
     WHERE client_id = $1
       AND LOWER(TRIM(COALESCE(first_name, ''))) = LOWER($2)
       AND LOWER(TRIM(COALESCE(last_name,  ''))) = LOWER($3)
     ORDER BY id ASC
     LIMIT 1`,[t,n,i]);if(0===o.rows.length){await e.query(`INSERT INTO client_contacts (client_id, first_name, last_name, phone, email, created_by)
       VALUES ($1, $2, $3, $4, $5, $6)`,[t,n||null,i||null,s||null,l||null,a]);return}await e.query(`UPDATE client_contacts
     SET phone      = $1,
         email      = $2,
         updated_at = CURRENT_TIMESTAMP
     WHERE id = $3`,[s||null,l||null,o.rows[0].id])}async function s(e,t,r){let i=t.company.trim(),s=t.nip.trim();if(""===i)return null;let l=t.address.trim(),o=t.sapId.trim(),u=t.firstName.trim(),c=t.lastName.trim(),p=t.phone.trim(),d=t.email.trim(),m=await a(e,i,s);if(null===m){let a=(await e.query(`INSERT INTO clients (company, nip, address, sap_id, first_name, last_name, phone, email, created_by)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       RETURNING id`,[i,s||null,l||null,o||null,u||null,c||null,p||null,d||null,r])).rows[0].id;return await n(e,a,t,r),a}return await e.query(`UPDATE clients
     SET company    = COALESCE(NULLIF(TRIM(company),    ''), $1),
         nip        = COALESCE(NULLIF(TRIM(nip),        ''), $2),
         address    = COALESCE(NULLIF(TRIM(address),    ''), $3),
         sap_id     = COALESCE(NULLIF(TRIM(sap_id),     ''), $4),
         first_name = COALESCE(NULLIF(TRIM(first_name), ''), $5),
         last_name  = COALESCE(NULLIF(TRIM(last_name),  ''), $6),
         phone      = COALESCE(NULLIF(TRIM(phone),      ''), $7),
         email      = COALESCE(NULLIF(TRIM(email),      ''), $8),
         updated_at = CURRENT_TIMESTAMP
     WHERE id = $9`,[i,s||null,l||null,o||null,u||null,c||null,p||null,d||null,m]),await n(e,m,t,r),m}r.d(t,{LM:()=>s,r8:()=>a,tS:()=>i})}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[9276,5972,2015,727],()=>r(37832));module.exports=a})();